#!/usr/bin/env node
/* =========================================================================
   build-present.js  --  generates kit/deck-present.html from kit/deck.html

   WHY THIS EXISTS
   ---------------
   kit/deck.html is two things at once: the file attendees download, and the
   source the slides PDF is printed from. It is also edited by several people
   on any given day. So the presenting artifact is generated FROM it rather
   than built INTO it.

   This script never touches slide content. It copies the <section class="s">
   markup byte for byte, swaps the <title>, appends a screen-only stylesheet,
   and replaces the deck's small nav script with the presenter one. If a slide
   changes in deck.html, re-run this and the presenting copy catches up.

   RUN:  node kit/build-present.js
   OUT:  kit/deck-present.html   (self-contained, opens from file://)
   ========================================================================= */

const fs = require('fs');
const path = require('path');

const DIR = __dirname;
const SRC = path.join(DIR, 'deck.html');
const OUT = path.join(DIR, 'deck-present.html');

let html = fs.readFileSync(SRC, 'utf8');

/* ---------- 1. sanity gates -------------------------------------------- */

const slideCount = (html.match(/<section class="s[^"]*"/g) || []).length;
if (slideCount === 0) {
  console.error('ABORT: found no <section class="s"> in deck.html');
  process.exit(1);
}

const external = (html.match(/(?:src|href)\s*=\s*["'](?!#|data:|mailto:)[^"']+["']/g) || [])
  .filter(a => /^(?:src|href)\s*=\s*["'](?:https?:)?\/\//.test(a));
if (external.length) {
  console.error('ABORT: deck.html has runtime-external references, offline is not safe:');
  external.forEach(a => console.error('   ' + a));
  process.exit(1);
}

const scripts = html.match(/<script[\s\S]*?<\/script>/g) || [];
if (scripts.length !== 1) {
  console.error(`ABORT: expected exactly 1 <script> in deck.html, found ${scripts.length}.`);
  console.error('The generator replaces that script. Two keydown handlers would double-advance.');
  process.exit(1);
}

/* The grain must survive. If someone scopes the print guard wrong and kills
   .s::after outside @media print, the deck loses its texture on screen. */
const printBlocks = html.match(/@media\s+print\s*\{[\s\S]*?\n\}/g) || [];
const grainKills = (html.match(/\.s::after\s*\{[^}]*display\s*:\s*none/g) || []).length;
const grainKillsInPrint = printBlocks.join('\n').match(/\.s::after\s*\{[^}]*display\s*:\s*none/g) || [];
if (grainKills > grainKillsInPrint.length) {
  console.error('ABORT: a rule hides .s::after (the film grain) outside @media print.');
  console.error('That would strip the texture from the full-screen presenting view.');
  process.exit(1);
}

/* ---------- 2. presenter stylesheet ------------------------------------ */

const CSS = `
<style id="present-mode">
/* =========================================================================
   PRESENTER MODE - generated by kit/build-present.js, do not hand edit.
   Everything here is @media screen. The deck's print rules are untouched,
   so Ctrl+P from this file still exports the same slides.
   ========================================================================= */
@media screen{

  :root{
    --pt-dur:.46s;
    --pt-ease:cubic-bezier(.22,.61,.36,1);
    --pt-rise:.30s;
  }

  html,body{background:#080706}

  /* The base deck hides slides with display:none, which cannot animate.
     Here only the slides taking part in the current transition are laid out
     (.live), so at most three of the thirty-seven ever paint. That is what
     keeps the per-slide film-grain filter cheap during motion. */
  .s{display:none}

  /* Safety net: if the script ever fails to run, slide one still renders
     instead of a black screen. The script adds #deck.ready and takes over. */
  .s:first-of-type{display:flex}
  #deck.ready .s:first-of-type{display:none}

  #deck.ready .s.live{
    display:flex;
    opacity:0;
    transform:translate3d(0,0,0);
    transition:opacity var(--pt-dur) var(--pt-ease),transform var(--pt-dur) var(--pt-ease);
    will-change:opacity,transform;
    z-index:1;
  }
  #deck.ready .s.live.on{opacity:1;transform:none;z-index:2}

  /* Directional carry. The offset is deliberately small: a full-width push
     reads as spectacle and is uncomfortable at full screen. 60px on a 1600px
     stage is enough to tell the eye which way the deck moved. */
  #deck.fwd .s.live.pre{opacity:0;transform:translate3d(62px,0,0) scale(.988)}
  #deck.bwd .s.live.pre{opacity:0;transform:translate3d(-62px,0,0) scale(.988)}
  #deck.fwd .s.live.out{opacity:0;transform:translate3d(-44px,0,0) scale(.994)}
  #deck.bwd .s.live.out{opacity:0;transform:translate3d(44px,0,0) scale(.994)}

  /* Grain relief during motion only. Two stacked multiply layers mid-crossfade
     is the one expensive frame in the whole deck; normal blend for under half
     a second is visually indistinguishable and costs nothing. Applied only
     when the runtime measures a slow frame, see ptGrainRelief in the script. */
  #deck.relief.moving .s::after{mix-blend-mode:normal;opacity:.32}

  /* Content stagger. Reads the eye down the slide: kicker, headline, body.
     Everything is finished inside .55s so it never makes him wait. The foot
     stamp and the QR tail are deliberately excluded, they are furniture and
     should simply be there. */
  @keyframes ptRise{from{opacity:0;transform:translate3d(0,17px,0)}to{opacity:1;transform:none}}
  #deck.ready .s.live.on>.kick,
  #deck.ready .s.live.on>h1,
  #deck.ready .s.live.on>h2,
  #deck.ready .s.live.on>p,
  #deck.ready .s.live.on>ol,
  #deck.ready .s.live.on>ul,
  #deck.ready .s.live.on>pre,
  #deck.ready .s.live.on>.mid,
  #deck.ready .s.live.on>.lead,
  #deck.ready .s.live.on>.body,
  #deck.ready .s.live.on>.cols,
  #deck.ready .s.live.on>.qrwrap,
  #deck.ready .s.live.on>.voices,
  #deck.ready .s.live.on>.mono-quote{animation:ptRise var(--pt-rise) var(--pt-ease) both}
  #deck.ready .s.live.on>*:nth-child(1){animation-delay:.06s}
  #deck.ready .s.live.on>*:nth-child(2){animation-delay:.13s}
  #deck.ready .s.live.on>*:nth-child(3){animation-delay:.20s}
  #deck.ready .s.live.on>*:nth-child(4){animation-delay:.26s}
  #deck.ready .s.live.on>*:nth-child(n+5){animation-delay:.31s}

  /* the deck's own in-slide progress bar is replaced by a viewport-fixed one */
  #bar{display:none!important}

  #ptbar{position:fixed;left:0;bottom:0;height:3px;width:0;z-index:40;
    background:linear-gradient(90deg,var(--amber-deep),var(--amber) 60%,var(--molten));
    box-shadow:0 0 16px rgba(232,99,42,.55);
    transition:width var(--pt-dur) var(--pt-ease)}

  /* Corner chrome. One stack, hard into the bottom-right corner, deliberately
     OUTSIDE the slide's 104px margin grid so it never reads as slide content.
     It does not appear on a plain next or back: the progress bar and the
     printed stamp already carry pacing, and a chip that lights up every time
     he clicks is a chip competing with him. Mouse move, ?, a typed number,
     Home, End or a jump summon it. */
  #ptchrome{position:fixed;right:11px;bottom:9px;z-index:41;display:flex;gap:7px;
    align-items:center;font-family:var(--mono);font-weight:500;font-size:12px;
    letter-spacing:.14em;text-transform:uppercase;
    opacity:0;transform:translateY(5px);pointer-events:none;
    transition:opacity .4s ease,transform .4s ease}
  #ptchrome.show{opacity:.9;transform:none}
  #ptchrome.off{display:none}
  #ptchrome b{font-weight:500;background:rgba(8,7,6,.86);color:#A99F90;
    border:1px solid rgba(232,99,42,.22);padding:6px 11px;display:block}
  #ptchrome b.clock{color:var(--molten);border-color:rgba(255,179,71,.42)}
  #ptchrome b.buf{color:#080706;background:var(--molten);border-color:var(--molten)}
  #ptchrome b.hint u{text-decoration:none;color:var(--molten)}
  #ptchrome b.hide{display:none}

  /* blank the screen, the key he will reach for when the room looks up */
  #ptblank{position:fixed;inset:0;z-index:60;background:#000;
    opacity:0;visibility:hidden;transition:opacity .26s ease,visibility .26s}
  #ptblank.on{opacity:1;visibility:visible}
  #ptblank.w{background:#F4EFE4}

  /* Jump list. Near-opaque on purpose: at .94 the cream slide underneath
     bled through hard enough to read the headline behind the list. */
  #ptjump{position:fixed;inset:0;z-index:70;background:rgba(8,7,6,.988);
    backdrop-filter:blur(10px);
    display:none;flex-direction:column;padding:5vh 0 3vh}
  #ptjump.on{display:flex;animation:ptFade .22s var(--pt-ease) both}
  @keyframes ptFade{from{opacity:0}to{opacity:1}}
  #ptjump header{flex:none;text-align:center;margin-bottom:26px;
    font-family:var(--mono);font-weight:500;font-size:14px;letter-spacing:.24em;
    text-transform:uppercase;color:#7E7568}
  #ptjump header em{font-style:normal;color:var(--molten)}
  #ptlist{flex:1;min-height:0;overflow-y:auto;width:min(940px,88vw);margin:0 auto;
    scrollbar-width:thin;scrollbar-color:rgba(232,99,42,.5) transparent}
  #ptlist .r{display:flex;gap:22px;align-items:baseline;padding:11px 20px;cursor:pointer;
    border-left:3px solid transparent;animation:ptRowIn .3s var(--pt-ease) both}
  @keyframes ptRowIn{from{opacity:0;transform:translateX(-14px)}to{opacity:1;transform:none}}
  #ptlist .r.gone{display:none}
  #ptlist .r span{font-family:var(--mono);font-weight:600;font-size:15px;letter-spacing:.14em;
    text-transform:uppercase;color:var(--amber);min-width:62px;flex:none;text-align:right}
  #ptlist .r em{font-style:normal;font-family:var(--body);font-size:20px;line-height:1.3;
    color:#B6AC9C;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  #ptlist .r.here span{color:var(--molten)}
  #ptlist .r.here em{color:#EFE7D6}
  #ptlist .r.sel{background:rgba(232,99,42,.14);border-left-color:var(--amber)}
  #ptlist .r.sel em{color:#EFE7D6}
  #ptjump footer{flex:none;text-align:center;margin-top:22px;
    font-family:var(--mono);font-weight:500;font-size:12px;letter-spacing:.2em;
    text-transform:uppercase;color:#6A6156}

  /* help overlay, restyled from the deck's own */
  #help{background:rgba(8,7,6,.988);backdrop-filter:blur(10px);
    flex-direction:column;text-transform:none;letter-spacing:0;line-height:1.6}
  #help .hh{font-family:var(--mono);font-size:14px;letter-spacing:.24em;
    text-transform:uppercase;color:#7E7568;margin-bottom:30px}
  #help table{border-collapse:collapse;font-family:var(--mono);font-size:16px}
  #help td{padding:8px 22px 8px 0;vertical-align:top}
  #help td:first-child{color:var(--molten);white-space:nowrap;font-weight:600}
  #help td:last-child{color:#B6AC9C}
  #help .hf{margin-top:32px;font-family:var(--mono);font-size:12px;letter-spacing:.2em;
    text-transform:uppercase;color:#6A6156}
}

/* Anyone who has asked their machine to calm down gets no motion, and every
   slide still lands on the same frame. */
@media screen and (prefers-reduced-motion:reduce){
  #deck.ready .s.live{transition:none!important}
  #deck.ready .s.live.on>*{animation:none!important}
  #ptbar{transition:none!important}
  #pthint{animation:none!important}
  #ptjump.on,#ptlist .r{animation:none!important}
}

/* Print stays a faithful export: the screen-only hidden states must not leak
   into the PDF, and none of the presenter chrome belongs on paper. */
@media print{
  .s{opacity:1!important;transform:none!important}
  .s>*{animation:none!important;opacity:1!important;transform:none!important}
  #ptbar,#ptchrome,#pthint,#ptblank,#ptjump{display:none!important}
}
</style>
`;

/* ---------- 3. presenter markup ---------------------------------------- */

const MARKUP = `
<div id="ptbar"></div>
<div id="ptchrome">
  <b class="buf hide" id="ptbuf"></b>
  <b class="clock hide" id="ptclock">00:00</b>
  <b class="hint" id="pthint"><u>F</u> full screen &nbsp;&middot;&nbsp; <u>?</u> keys</b>
  <b id="ptcount">1 / ${slideCount}</b>
</div>
<div id="ptblank"></div>
<div id="ptjump">
  <header>Jump to slide &nbsp;<em>&uarr; &darr;</em>&nbsp; move &nbsp;<em>enter</em>&nbsp; go &nbsp;<em>esc</em>&nbsp; back</header>
  <div id="ptlist"></div>
  <footer>type to filter</footer>
</div>
`;

/* ---------- 4. presenter script ---------------------------------------- */

const JS = `
<script>
/* Presenter runtime. No modules, no storage, no network: all three of those
   fail or throw under file:// on at least one browser, and this file has to
   open by double click from a Downloads folder on a machine that has never
   seen it. Plain script, plain DOM, everything wrapped where it can throw. */
(function(){
  var deck   = document.getElementById('deck');
  var stage  = document.getElementById('stage');
  var slides = Array.prototype.slice.call(stage.querySelectorAll('.s'));
  var N      = slides.length;
  if(!N) return;

  var help   = document.getElementById('help');
  var ptbar  = document.getElementById('ptbar');
  var chrome = document.getElementById('ptchrome');
  var count  = document.getElementById('ptcount');
  var clock  = document.getElementById('ptclock');
  var bufEl  = document.getElementById('ptbuf');
  var hint   = document.getElementById('pthint');
  var blank  = document.getElementById('ptblank');
  var jump   = document.getElementById('ptjump');
  var list   = document.getElementById('ptlist');

  var DUR = 460;
  var i = 0, pending = null, sel = 0, buf = '', bufT = null;

  slides.forEach(function(s){ s._base = s.className; });

  /* ---- scale the fixed 1600x900 stage into whatever screen he is on ---- */
  function fit(){
    stage.style.transform = 'scale(' +
      Math.min(window.innerWidth / 1600, window.innerHeight / 900) + ')';
  }
  window.addEventListener('resize', fit);
  document.addEventListener('fullscreenchange', function(){
    fit();
    if(document.fullscreenElement && hint) hint.classList.add('hide');
  });
  fit();

  /* ---- read the printed stamp and headline off the frozen markup ------- */
  /* Headlines are broken with <br>, and textContent welds the two halves
     together: "AI WITHOUTGETTING BURNED". Swap every break for a space on a
     clone so the frozen markup is never touched. */
  function flatten(el){
    if(!el) return '';
    var c = el.cloneNode(true);
    Array.prototype.forEach.call(c.querySelectorAll('br'), function(br){
      br.parentNode.replaceChild(document.createTextNode(' '), br);
    });
    return (c.textContent || '').replace(/\\s+/g, ' ').trim();
  }

  var meta = slides.map(function(s, n){
    var label = '';
    var foot = s.querySelector('.foot');
    if(foot){
      var sp = foot.querySelectorAll('span');
      if(sp.length){
        var last = (sp[sp.length - 1].textContent || '').replace(/\\s+/g, '').trim();
        if(/^[0-9]{1,2}$|^[A-Z]$/.test(last)) label = last;
      }
    }
    var t = flatten(s.querySelector('h1'));
    if(!t) t = flatten(s.querySelector('.lead, .body, .mono-quote, ol li, ul li'));
    return { label: label, title: t || ('Slide ' + (n + 1)), n: n };
  });

  /* Several slides legitimately share a headline: two say AI WITHOUT GETTING
     BURNED, three say DO THIS NOW. A list where four rows read the same is a
     list he cannot navigate under pressure, so repeats pick up their kicker.
     Three of them share the kicker "Your turn" too, so anything still tied
     after that takes a bite of its own body copy. */
  function tally(){
    var f = {};
    meta.forEach(function(m){ f[m.title] = (f[m.title] || 0) + 1; });
    return f;
  }
  var freq = tally();
  meta.forEach(function(m, n){
    if(freq[m.title] > 1){
      var k = flatten(slides[n].querySelector('.kick b'));
      if(k) m.title += '  \\u00b7  ' + k;
    }
  });
  freq = tally();
  meta.forEach(function(m, n){
    if(freq[m.title] > 1){
      var d = flatten(slides[n].querySelector('.lead, .body, ol.stack li, ul.plain li, .mono-quote'));
      if(d) m.title += '  \\u00b7  ' + d.slice(0, 44);
    }
  });
  meta.forEach(function(m){
    if(m.title.length > 90) m.title = m.title.slice(0, 89) + '\\u2026';
  });

  /* ---- probe history once, file:// can refuse replaceState ------------- */
  var startHash = parseInt((location.hash || '').replace('#', ''), 10);
  var canHist = true;
  try { history.replaceState(null, '', location.hash || '#0'); }
  catch(e){ canHist = false; }

  /* ---- grain relief: only switches on if a transition actually drops --- */
  var slowFrames = 0, relief = false;
  function watchFrame(){
    if(relief) return;
    var t0 = performance.now(), n = 0, worst = 0;
    (function step(){
      var t = performance.now(), d = t - t0;
      t0 = t;
      if(n++ > 1 && d > worst) worst = d;
      if(n < 26) requestAnimationFrame(step);
      else if(worst > 34){
        if(++slowFrames >= 2){ relief = true; deck.classList.add('relief'); }
      }
    })();
  }

  /* ---- the transition -------------------------------------------------- */
  function show(n, instant){
    if(n < 0) n = 0;
    if(n > N - 1) n = N - 1;
    if(n === i && slides[i].classList.contains('on')) return;

    deck.classList.remove('fwd', 'bwd');
    deck.classList.add(n > i ? 'fwd' : 'bwd');

    /* Hard settle anything still in flight. He will click faster than the
       animation at least once on Thursday, and a stranded half-faded slide
       on the wall is not recoverable in front of a room. */
    if(pending){ clearTimeout(pending); pending = null; }
    slides.forEach(function(s, k){ if(k !== n && k !== i) s.className = s._base; });

    var prev = slides[i], next = slides[n];

    if(instant){
      slides.forEach(function(s){ s.className = s._base; });
      next.className = next._base + ' live on';
      i = n; paint(); warm(); return;
    }

    next.className = next._base + ' live pre';
    void next.offsetWidth;                       /* commit the pre state */
    next.classList.remove('pre');
    next.classList.add('on');

    prev.classList.remove('on');
    prev.classList.add('out');
    deck.classList.add('moving');
    watchFrame();

    var dead = prev;
    pending = setTimeout(function(){
      dead.className = dead._base;
      deck.classList.remove('moving');
      pending = null;
      warm();
    }, DUR + 70);

    i = n;
    paint();
  }

  /* The first visit to any slide was costing a long frame, because that slide
     had never been laid out or rasterised before: display:none skips both.
     Measured at 688ms on the very first transition against a 17ms median.
     So once a transition has settled, quietly lay out the slides on either
     side at opacity zero, in idle time, where a long frame costs nothing.
     show() settles everything except the current and the target, so this
     never grows past three live slides. */
  function warm(){
    [i - 1, i + 1].forEach(function(k){
      var s = slides[k];
      if(!s || k === i || s.classList.contains('live')) return;
      s.classList.add('live');
      void s.offsetHeight;                       /* layout */
      if(s._rastered) return;
      /* Layout alone was not enough: a layer at opacity zero is laid out but
         never painted, so the grain and the type still rasterised on the
         click. Two frames at two tenths of one percent, behind a fully opaque
         slide, forces the paint here in the quiet instead of there. */
      s._rastered = true;
      s.style.opacity = '.002';
      requestAnimationFrame(function(){
        requestAnimationFrame(function(){ s.style.opacity = ''; });
      });
    });
  }

  function paint(){
    ptbar.style.width = (N > 1 ? (i / (N - 1)) * 100 : 100) + '%';
    count.textContent = (i + 1) + ' / ' + N;
    if(canHist){ try { history.replaceState(null, '', '#' + i); } catch(e){ canHist = false; } }
    markHere();
  }

  /* ---- corner chrome, summoned rather than automatic --------------------
     paint() deliberately does NOT call this. Advancing a slide must not light
     up a chip in the corner of the wall every single time he clicks. The bar
     and the printed stamp carry pacing; this is for when he goes looking. */
  var idleT = null;
  function bump(hold){
    chrome.classList.add('show');
    clearTimeout(idleT);
    if(t0 || hold === true) return;              /* timer on, or held open */
    idleT = setTimeout(function(){ chrome.classList.remove('show'); }, 2200);
  }

  /* ---- elapsed timer, off unless he asks for it ------------------------ */
  var t0 = null, tick = null;
  function two(v){ return (v < 10 ? '0' : '') + v; }
  function renderClock(){
    if(!t0) return;
    var s = Math.floor((Date.now() - t0) / 1000);
    clock.textContent = two(Math.floor(s / 60)) + ':' + two(s % 60);
  }
  function timerToggle(){
    if(t0){
      t0 = null; clearInterval(tick); tick = null;
      clock.classList.add('hide'); clock.textContent = '00:00';
    } else {
      t0 = Date.now();
      clock.classList.remove('hide');
      renderClock();
      tick = setInterval(renderClock, 1000);
    }
    bump();
  }
  function timerReset(){ if(t0){ t0 = Date.now(); renderClock(); bump(); } }

  /* ---- blank ------------------------------------------------------------ */
  function setBlank(mode){
    if(!mode){ blank.className = ''; return; }
    blank.className = 'on' + (mode === 'w' ? ' w' : '');
  }
  function blanked(){ return blank.classList.contains('on'); }

  /* ---- jump list -------------------------------------------------------- */
  var rows = meta.map(function(m){
    var r = document.createElement('div');
    r.className = 'r';
    var a = document.createElement('span');
    a.textContent = m.label || ('\\u00b7' + (m.n + 1));
    var b = document.createElement('em');
    b.textContent = m.title;
    r.appendChild(a); r.appendChild(b);
    r.addEventListener('click', function(ev){
      ev.stopPropagation();
      closeJump(); show(m.n);
    });
    list.appendChild(r);
    return r;
  });
  function markHere(){
    rows.forEach(function(r, k){ r.classList.toggle('here', k === i); });
  }
  function visibleRows(){
    var out = [];
    rows.forEach(function(r, k){ if(!r.classList.contains('gone')) out.push(k); });
    return out;
  }
  function drawSel(){
    rows.forEach(function(r, k){ r.classList.toggle('sel', k === sel); });
    /* centre, not nearest: nearest parked the current slide flush against the
       bottom edge where the footer clipped it */
    if(rows[sel] && rows[sel].scrollIntoView) rows[sel].scrollIntoView({ block: 'center' });
  }
  function filterJump(){
    var q = buf.toLowerCase();
    rows.forEach(function(r, k){
      var hit = !q ||
        meta[k].label.toLowerCase() === q ||
        meta[k].label.toLowerCase().indexOf(q) === 0 ||
        meta[k].title.toLowerCase().indexOf(q) > -1 ||
        String(k + 1) === q;
      r.classList.toggle('gone', !hit);
    });
    var vis = visibleRows();
    if(vis.indexOf(sel) === -1 && vis.length) sel = vis[0];
    drawSel();
  }
  function openJump(){
    jump.classList.add('on');
    chrome.classList.add('off');                 /* nothing behind the sheet */
    buf = ''; showBuf();
    rows.forEach(function(r){ r.classList.remove('gone'); });
    sel = i; drawSel();
  }
  function closeJump(){
    jump.classList.remove('on');
    chrome.classList.remove('off');
    buf = ''; showBuf(); bump();
  }
  function jumpOpen(){ return jump.classList.contains('on'); }

  /* ---- number buffer outside the jump list ------------------------------ */
  function showBuf(){
    if(buf){ bufEl.textContent = buf + '\\u2026'; bufEl.classList.remove('hide'); bump(); }
    else bufEl.classList.add('hide');
  }
  function commitBuf(){
    var q = buf; buf = ''; showBuf();
    if(!q) return false;
    for(var k = 0; k < meta.length; k++){
      if(meta[k].label && meta[k].label.toLowerCase() === q.toLowerCase()){ show(k); bump(); return true; }
    }
    var p = parseInt(q, 10);
    if(!isNaN(p)) show(Math.max(0, Math.min(N - 1, p - 1)));
    bump();
    return true;
  }

  /* ---- keys ------------------------------------------------------------- */
  function fullscreen(){
    try{
      if(document.fullscreenElement) document.exitFullscreen();
      else document.documentElement.requestFullscreen();
    }catch(e){}
  }

  document.addEventListener('keydown', function(e){
    if(e.ctrlKey || e.metaKey || e.altKey) return;   /* leave Ctrl+P alone */
    var k = e.key;

    /* jump list owns the keyboard while it is open */
    if(jumpOpen()){
      if(k === 'Escape'){ e.preventDefault(); closeJump(); return; }
      if(k === 'ArrowDown' || k === 'ArrowRight'){
        e.preventDefault();
        var v = visibleRows(), p = v.indexOf(sel);
        if(v.length) sel = v[Math.min(v.length - 1, p + 1)];
        drawSel(); return;
      }
      if(k === 'ArrowUp' || k === 'ArrowLeft'){
        e.preventDefault();
        var v2 = visibleRows(), p2 = v2.indexOf(sel);
        if(v2.length) sel = v2[Math.max(0, p2 - 1)];
        drawSel(); return;
      }
      if(k === 'Enter'){ e.preventDefault(); var t = sel; closeJump(); show(t); return; }
      if(k === 'Backspace'){ e.preventDefault(); buf = buf.slice(0, -1); showBuf(); filterJump(); return; }
      if(k.length === 1 && k !== ' '){ e.preventDefault(); buf += k; showBuf(); filterJump(); return; }
      return;
    }

    if(help.classList.contains('on')){
      if(k === 'Escape' || k === '?' || k === '/'){ e.preventDefault(); help.classList.remove('on'); }
      return;
    }

    /* any key clears a blank screen, which is what the hand expects */
    if(blanked()){
      e.preventDefault();
      setBlank(null);
      if(k === 'ArrowRight' || k === ' ' || k === 'PageDown') show(i + 1);
      return;
    }

    if(k === 'ArrowRight' || k === ' ' || k === 'PageDown'){ e.preventDefault(); show(i + 1); }
    else if(k === 'Enter'){ e.preventDefault(); if(!commitBuf()) show(i + 1); }
    else if(k === 'ArrowLeft' || k === 'PageUp' || k === 'Backspace'){ e.preventDefault(); show(i - 1); }
    else if(k === 'ArrowDown'){ e.preventDefault(); show(i + 1); }
    else if(k === 'ArrowUp'){ e.preventDefault(); show(i - 1); }
    else if(k === 'Home'){ e.preventDefault(); show(0); bump(); }
    else if(k === 'End'){ e.preventDefault(); show(N - 1); bump(); }
    else if(k === 'f' || k === 'F'){ e.preventDefault(); fullscreen(); }
    else if(k === 'b' || k === 'B' || k === '.'){ e.preventDefault(); setBlank('b'); }
    else if(k === 'w' || k === 'W' || k === ','){ e.preventDefault(); setBlank('w'); }
    else if(k === 'o' || k === 'O' || k === 'g' || k === 'G'){ e.preventDefault(); openJump(); }
    else if(k === 't'){ e.preventDefault(); timerToggle(); }
    else if(k === 'T'){ e.preventDefault(); timerReset(); }
    else if(k === '?' || k === '/'){ e.preventDefault(); help.classList.add('on'); }
    else if(k === 'Escape'){ e.preventDefault(); buf = ''; showBuf(); }
    else if(k >= '0' && k <= '9'){
      e.preventDefault(); buf += k; showBuf();
      clearTimeout(bufT); bufT = setTimeout(function(){ buf = ''; showBuf(); }, 2400);
    }
    else if(k.length === 1 && /[a-dA-D]/.test(k)){
      /* the closing slides are stamped A B C D, not numbers */
      e.preventDefault(); buf = k.toUpperCase(); commitBuf();
    }
  });

  /* ---- pointer and touch ------------------------------------------------ */
  document.addEventListener('click', function(e){
    if(jumpOpen()) return;
    if(help.classList.contains('on')){ help.classList.remove('on'); return; }
    if(blanked()){ setBlank(null); return; }
    show(e.clientX < window.innerWidth / 3 ? i - 1 : i + 1);
  });
  document.addEventListener('mousemove', bump);

  var tx = 0, ty = 0;
  document.addEventListener('touchstart', function(e){
    if(!e.touches.length) return;
    tx = e.touches[0].clientX; ty = e.touches[0].clientY;
  }, { passive: true });
  document.addEventListener('touchend', function(e){
    if(!e.changedTouches.length) return;
    var dx = e.changedTouches[0].clientX - tx;
    var dy = e.changedTouches[0].clientY - ty;
    if(Math.abs(dx) > 48 && Math.abs(dx) > Math.abs(dy)){ show(dx < 0 ? i + 1 : i - 1); }
  }, { passive: true });

  /* ---- help sheet ------------------------------------------------------- */
  help.innerHTML =
    '<div class="hh">Keys</div>' +
    '<table>' +
    '<tr><td>&rarr; &nbsp; space &nbsp; page down</td><td>next slide, and what the clicker sends</td></tr>' +
    '<tr><td>&larr; &nbsp; page up &nbsp; backspace</td><td>previous slide</td></tr>' +
    '<tr><td>home &nbsp; end</td><td>first slide &nbsp; last slide</td></tr>' +
    '<tr><td>O &nbsp; or &nbsp; G</td><td>jump list, type to filter</td></tr>' +
    '<tr><td>digits then enter</td><td>go to that stamped slide number</td></tr>' +
    '<tr><td>A &nbsp; B &nbsp; C &nbsp; D</td><td>go to the lettered closing slides</td></tr>' +
    '<tr><td>B &nbsp; or &nbsp; .</td><td>black the screen, any key brings it back</td></tr>' +
    '<tr><td>W &nbsp; or &nbsp; ,</td><td>white the screen</td></tr>' +
    '<tr><td>F</td><td>full screen</td></tr>' +
    '<tr><td>T &nbsp; / &nbsp; shift T</td><td>elapsed timer on or off / restart it</td></tr>' +
    '<tr><td>esc</td><td>close this, or clear a typed number</td></tr>' +
    '</table>' +
    '<div class="hf">' + N + ' slides &nbsp;&middot;&nbsp; runs offline, nothing is fetched</div>';

  /* ---- go --------------------------------------------------------------- */
  deck.classList.add('ready');
  show(isNaN(startHash) ? 0 : Math.max(0, Math.min(N - 1, startHash)), true);

  /* The one nudge he gets, and it lives in the corner stack with everything
     else. It used to float in the middle of the bottom edge, which put a
     black box straight across the wifi write-in rules on the holding slide,
     the slide that stays on the wall longest while people are walking in. */
  bump(true);
  setTimeout(function(){ hint.classList.add('hide'); bump(); }, 6500);
})();
<\/script>
`;

/* ---------- 4b. house rules on the chrome I wrote ----------------------- */
/* No em dashes anywhere, including the help sheet. One slipped into the key
   list on the first pass and only turned up when the overlay was looked at. */
const mine = CSS + MARKUP + JS;
const dashes = mine.match(/—|&mdash;/g) || [];
if (dashes.length) {
  console.error(`ABORT: ${dashes.length} em dash(es) in the presenter chrome.`);
  process.exit(1);
}

/* ---------- 5. assemble ------------------------------------------------- */

let out = html;

out = out.replace(/<title>([\s\S]*?)<\/title>/,
  (m, t) => `<title>${t.replace(/\s*-\s*Attendee Copy\s*$/, '')} - Presenting Copy</title>`);

out = out.replace('</head>', CSS + '</head>');

/* the presenter markup goes right after the deck container, before the
   original nav script, so overlays sit above the stage in paint order */
out = out.replace(scripts[0], MARKUP + JS);

/* a generated-file banner so nobody hand edits this and loses it */
out = out.replace('<head>',
`<head>
<!-- =========================================================================
     GENERATED FILE. Do not hand edit.
     Source: kit/deck.html    Generator: kit/build-present.js
     Run "node kit/build-present.js" to rebuild after any slide change.

     This is the copy Boubacar presents from. Same ${slideCount} slides, same order,
     same printed stamps, same film grain. Screen-only presentation layer added.
     Fully self-contained: fonts are base64 woff2, the QR is inline SVG,
     nothing is fetched at runtime. Opens by double click from file://.
     ========================================================================= -->`);

fs.writeFileSync(OUT, out, 'utf8');

/* ---------- 6. verify what was written ---------------------------------- */

const check = fs.readFileSync(OUT, 'utf8');
const outSlides = (check.match(/<section class="s[^"]*"/g) || []).length;
const outScripts = (check.match(/<script/g) || []).length;

if (outSlides !== slideCount) {
  console.error(`ABORT: wrote ${outSlides} slides but source has ${slideCount}. Output deleted.`);
  fs.unlinkSync(OUT);
  process.exit(1);
}

/* The slide markup must be byte-identical, not merely the same count. Grab
   everything from the deck container to the end of the final section. */
const grab = s => {
  const a = s.indexOf('<div id="deck">');
  const b = s.lastIndexOf('</section>');
  return (a < 0 || b < 0) ? '' : s.slice(a, b + 10);
};
const srcSlides = grab(html);
const outSlidesHtml = grab(check);
if (!srcSlides || srcSlides !== outSlidesHtml) {
  console.error('ABORT: slide markup differs from the source. Output deleted.');
  fs.unlinkSync(OUT);
  process.exit(1);
}
console.log('  markup      byte-identical, ' + srcSlides.length + ' chars of slides copied verbatim');

console.log('deck-present.html written');
console.log('  slides      ' + outSlides + ' (identical markup to deck.html)');
console.log('  scripts     ' + outScripts + ' (presenter runtime only)');
console.log('  size        ' + (check.length / 1024).toFixed(0) + ' KB');
console.log('  external    0 refs, safe offline from file://');
